language: python
sudo: required
dist: xenial
python:
- '3.7'
install:
- pip install tox-travis
- pip install coveralls
script:
- tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: cmaclell
  password:
    secure: w+mXS1xbHJS6OX5z1/B3aPxfZEJr280SmVuCcxrIlUz+okiydmCvbNFMx4/o7cikQwyngmxtK+AhOs3qxCv9gsfax/rPcV/dJSO2vpXVUSVsDyvDsorq8JSyy7n9YSTv92pomUKztTAPDPIA45K+dvBh+ioyM8JEjr5U1EAndj8U69NL7kuGXt95DdvyG7PweprTgDW8HV+5oX7SCs5OkxB0DJd9P6bUed7tSdf2JIOLeM/3HGIfuGtAFz3j1lbSnFPjNKLIK1/FtRpOPVW43yGsztm3Jv8ebTDCLuO4tqGoMgAII8LSy8vhHDv59RuG8meWEYf0PxbIC5e24Miu4cfnSSj+pRNVeiVDtI4MckD/wdRe+ZRvapE7l+w26qfaLNqdTfZR8IJ+P1Q2vYdmR6NHULxf6QtO7lqbzcF/TJaRdS9zTrBFT/1plDnOnTmPZZrMAOcfwK+c2WEKBVSkAcKG2HlD5VROR1TbwpVKdsi2RuE2TFKppSk+kl9YGITQae9LU82cWUnT2VzCGpeOv5/EjC+PtOK3pNbx4b+avuYTDkQ5oaSMnpfjuXvYic7N0VP8sB+NzxaFkLqrs2Qr3tPmOV58cCbceH25mht7oCI11IgpjLqLFtykS2UH7VzANM2nowJtUCH+YtAyjXR3yIrfhI2H+OePq5bO3UT/KUQ=
  on:
    tags: true
  skip_existing: true
