language: python
sudo: required
dist: xenial
python:
- '3.7'
install:
- pip install tox-travis
- pip install coveralls
script:
- tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: cmaclell
  skip_existing: true
  password:
    secure: iGiXIqo7GO0ynyw7yRYsl1DzmVAvke1sBWoqgXQoI4ChJOySKzY3ysqwa1BCcYxr6zZL3KEZObLBuAiVOkX7uX5o1T6xmZ6CWvAxEoSlvA27btEwq2cwsCsEibjIKgMZE63vdyBZEvgws53xC/k77N2S9KHtzo2LmRDjx13oasKJMGugS8o+KsESEgcLsgMe8fiEwXmIGY0OBb17qnx/7vA6x7WRjtdwKsnia3suuobmjvQ9txhTR3NoODo2Hb9Yv2lytU2aq+EU8tLNMeFRw8ltLmt0PL5Va0EEmDdmw/fVSIzIRe8nJcpAOe8xCeNFgz6K44GE75ksj1B3MZH479bLP3dXoKLxzL3CzF4KhEH3JBrXJc7fd4A40Aoif/oQQp27wUUqHOyJdw+Z+W4fFH/1BYuI5KxBLuPB0ufkCZoe0PfUTePccei94ekg3Euabn6Q+L50wTFHhHr5ZSGaEm0KV5CC7pem0rUQrim1vlyz2lfTjAl5HkfXGROXSP9WARsrOaEh6PM5rO8LS2QPGeTr4z1Qu9OHQcri+NUwKrBIiRpa24IazneqVMxjdMAubx0/zYu1PnqFDCbKyH6Kq0d9Wn5TMq4CGKcQ9JeBaY2rPxZkS5OcVUQ+zoUL3IZ7vZM0ytsGOZzP/lafyPrhe54hg8MaKdQQUR7BJiNZvL0=
