language: python
sudo: required
dist: xenial
python:
- '3.7'
install:
- pip install tox-travis
- pip install coveralls
script:
- tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: cmaclell
  skip_existing: true
  password:
    secure: DyXQASm8rIjhD1zCWPE0kokbDvtHtlKpJKi++odFw8rfOWz26pKC3pM7U2OfELWiVMCkn7NhmmKQnFApvNkCDQJ6z63GxapDTsroSO5pPvg2eEltfUQb1yxw97EBl5VQhxDPk7yAFowUOCZp65BNNQv+T/idzCKiz8GIXnxOy9zaoRl/j7FRXBg5/QLdr04P2+W2yLIur74eCFmOr4EgLnLZf/yVb6lsAHDwLduqr4b9gWC2P6YJenUEhnuJ61oOxZmt8L26UrAZlyFrlu51nLNPBIyTyVmC3/KO/9SD6Hn5N4scpPNMpbzZ5qCmpqdXdcDmovkDctaVzzsQR7A6/uLTEPnTb19iyxucaagPfF/KsBx0iRtOcqNNyAI4EgkTolRc6jIFe/UL4LUwgyirl8cOtLdPNiMyp2nXGH2aQWkLp8e4C5Px3bZt43qbRrG94hw6TbT/nNUbib38ejlTrtNSGIqtjNFBowI3UmSzPLPvwEYrM6QlX+wG+s3zFd8+GxlMzRI/GklchE7Ayl/Nij1tpvG7pWbLcEHZxs1nnr7J4Kyt9BwgqIIZYh+4PNsKMhEi2FuOBLK2JDiKe/rQmDF5nkyoX4eshOgKa2F6CbvtHZ5UGrKgxrmV5wz5dKWpmY87aPnHXu/Fwr761h/QX0VGrGf4Y+zXsE/FZemMlsE=
