language: python
sudo: required
dist: xenial
python:
- '3.7'
install:
- pip install tox-travis
- pip install coveralls
script:
- tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: cmaclell
  skip_existing: true
  password:
    secure: nqWf6/bUZZGzmGmFwrlm9YPSPCZBwSt7OWv0BDi81ji6SZAL7+liSnJq/JTaqQLNy08gtzYC07G6en95ymJJjQ9uSh92jH2HXt+LyVgS9k3+REc2Rjmjg5ST74vr2tTFSUR3CltjY/D8eqJsdJxN7UcGNNa9Yt6MYnLY3njNLFKBmAmNQhXt+TGKYqFnCehKISNtrTm1MUtzD7U3LRqLgwLmSQC88sPqg6cXgVnq3OSReTV3yhqPV06putWzSS7AYEt7q5z9CdLnh8th0F2FwpIobobi+9fDJUNw/rJZEO4a2evnVgUuXiL1iJH959a9+c3t+t6kmYjGtWHWNQEgQqlOdcq2YhCPW5hG1sPaMRkhYw65AErAjRiDEWMokONj3YGFu7yk0l13tOoCK6yoTfuqe1YPjPCMKAesnmRzgFOZRI1OugXKQs8tBC4IPj7IlNojRT9OflC/i18NJRlQY6EmogsSxC/hI68ejLqjIRKwo2csHTrJNe25j4N4++oVya99dH4kee+yuWd8VqtAN6cnrtcO+PEbukqwpUj8idsLbMyhOl/7J46lI0Q7FcPTlfNEZhQk6lVFQ5siQeV+jmskncr/hLo7tI0zwTVXpxU/H8xb/DQJV1LGCSLMtdxqelBOMHMoNr5DEVvJCpExzc7/OPfuTH4lG+cWD0q5bsY=
